# Vim Compatibility set -sg escape-time 0
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# Change Prefix Key
unbind C-b
unbind C-Space
set -g prefix C-Space

# Kill Commands
unbind x
unbind X
unbind M-x
bind x kill-pane
bind X kill-window
bind -n M-x kill-server

# Vim Navigation
unbind C-h
unbind C-h
unbind C-k
unbind C-l
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Change New Pane Keys
unbind v
unbind h
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# Resize Panes
bind -n C-M-h resize-pane -L 5
bind -n C-M-j resize-pane -D 5
bind -n C-M-k resize-pane -U 5
bind -n C-M-l resize-pane -R 5

# Reload tmux Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded ~/.config/tmux/tmux.conf"

# Clear Screen
bind -n M-l if-shell -b "[ -z $TMUX ]" "send-keys 'clear' \; send-keys 'Enter'" 

# Window Keybinds
unbind n
unbind w
unbind M-j
unbind M-k

bind n command-prompt "rename-window '%%'"
bind w new-window -c "#{pane_current_path}"
bind -n M-j previous-window
bind -n M-k next-window

# Copy Mode
set-window-option -g mode-keys vi
unbind -T copy-mode-vi Space; #Default for begin-selection
unbind -T copy-mode-vi Enter; #Default for copy-selection

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"`

# Colors

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'o0th/tmux-nova'
# Theme
set -g @nova-rows 0
set -g @nova-nerdfonts "true"
set -g @nova-nerdfonts_left "true"
set -g @nova-nerdfonts_right "true"
set -g @nova-status-style-bg "#1b1b1b"
set -g @nova-status-style-active-bg "#ff6600"
set -g @nova-status-style-active-fg "#070707"
set -g @nova-pane-border-style "#1b1b1b"
set -g @nova-pane-active-border-style "#ff6600"
  # Mode Segment
set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#2b6dff #070707"
  # Whoami Segment
set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#ff3232 #070707"
  # System Stats
    #CPU
set -g @cpu_percentage_format "%5.1f%%"
set -g @nova-segment-cpu "#(~/.config/tmux/plugins/tmux-cpu/scripts/cpu_percentage.sh)"
set -g @nova-segment-cpu-colors "#00c8ff #070707"

    #RAM
set -g @ram_percentage_format "%5.1f%%"
set -g @nova-segment-ram "#(~/.config/tmux/plugins/tmux-cpu/scripts/ram_percentage.sh)"
set -g @nova-segment-ram-colors "#bbff00 #070707"

    #GPU
set -g @gpu_percentage_format "%5.1f%%"
set -g @nova-segment-gpu "﬙#(~/.config/tmux/plugins/tmux-cpu/scripts/gpu_percentage.sh)"
set -g @nova-segment-gpu-colors "#ff8800 #070707"

  # Place Segments
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "gpu ram cpu whoami"

run -b '~/.config/tmux/plugins/tpm/tpm'
