default_keybinds = false


[theme]
primary = "#F1F1F1"
secondary = "#DCDCDC"
title = "#FF6600"
playing = "#FF6600"
playing_selected = "#0000FF"
playing_bg = "#181818"
highlight_bg = "#FF6600"
error = "#FFE4E4"
error_bg = "#A50000"
statusbar = "#000000"
statusbar_progress = "#FF6600"
statusbar_bg = "#FF6600"
cmdline = "#D27436"
cmdline_bg = "#444444"

[keybindings]
# General
"?" = "help"
"Esc" = "quit"
"U" = "update"
"x" = "share selected"
"X" = "share current"
"d" = "delete"
"c" = "clear"
"Ctrl+v" = "insert"
"Ctrl+s" = "save queue"
"s" = "save"
"q" = "back"

# Playback
"=" = "volup 5"
"-" = "voldown 5"
"p" = "previous"
"n" = "next"
"Enter" = "play"
";" = "play"
"." = "playnext"
"S" = "stop"
"b" = "seek -5000"
"f" = "seek +5000"
"B" = "seek -10000"
"F" = "seek +10000"
"z" = "shuffle"
"r" = "repeat"
"Space" = "playpause"

# Navigation
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"J" = "move down 5"
"K" = "move up 5"
"g" = "move top"
"G" = "move bottom"
"F1" = "focus queue"
"F2" = "focus search"
"F3" = "focus library"
"o" = "open selected"
"O" = "open current"
"a" = "goto album"
"A" = "goto artist"
